# Generated by Django 5.0.7 on 2024-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Villas',
        ),
    ]
