# Generated by Django 5.0.7 on 2024-08-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilerproducs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobiler_products',
            name='product_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('land', 'land'), ('villa', 'villa'), ('riad', 'riad')], default='apartment', max_length=10),
        ),
        migrations.AlterField(
            model_name='immobiler_products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
