# Generated by Django 5.0.7 on 2024-08-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilerproducs', '0006_alter_immobiler_products_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobiler_products',
            name='product_address',
            field=models.CharField(choices=[('marrakech', 'marrakech'), ('fez', 'fez'), ('essaouira', 'essaouira'), ('tanger', 'tanger'), ('casablanca', 'casablanca'), ('nadour', 'nadour'), ('dakhla', 'dakhla')], max_length=100),
        ),
    ]
