# Generated by Django 5.0.7 on 2024-08-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villa_name', models.CharField(max_length=100)),
                ('villa_address', models.CharField(max_length=100)),
                ('villa_price', models.IntegerField()),
                ('villa_image', models.ImageField(upload_to='images/')),
                ('villa_description', models.TextField()),
                ('villa_status', models.BooleanField(default=False)),
                ('villa_area', models.CharField(max_length=20)),
            ],
        ),
    ]
