# Generated by Django 5.0.7 on 2024-08-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilerproducs', '0002_immobiler_products_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobiler_products',
            name='product_images',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
