# Generated by Django 5.0.7 on 2024-08-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilerproducs', '0003_alter_immobiler_products_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobiler_products',
            name='product_images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='immobiler_products',
            name='product_type',
            field=models.CharField(choices='', default='', max_length=10),
        ),
    ]
