# Generated by Django 5.0.7 on 2024-08-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilerproducs', '0004_alter_immobiler_products_product_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobiler_products',
            name='product_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('land', 'land'), ('villa', 'villa'), ('riad', 'riad')], default='', max_length=10),
        ),
    ]
