# Generated by Django 5.0.7 on 2024-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_contentText', models.TextField()),
                ('blog_title_image', models.ImageField(upload_to='')),
                ('blog_TimeCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
