# Generated by Django 5.0.7 on 2024-08-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_table',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blog_table',
            name='blog_title_image',
            field=models.ImageField(upload_to='blogs/'),
        ),
    ]
